### ISSUE TITLE
Metanorma invocation API

### ISSUE THREAD

**Issue by strogonoff** [paneron/paneron#41]
Metanorma now can be invoked using two new methods available via `DatasetContext`, [`invokeMetanorma()` and `useMetanormaInvocationStatus`](https://github.com/paneron/extension-kit/blob/bff7d63afb120b05b1ae64c48307b57343a3caf4/src/types/renderer.ts#L46-L57).

- `invokeMetanorma()` should be called as `await invokeMetanorma({ cliArgs: […] });` in e.g. button handler. It accepts a list of strings under `{ cliArgs: … }`, which will be passed to the [underlying `metanorma` executable](https://github.com/metanorma/packed-mn/releases/tag/v1.4.14). I’m not sure which flags are supported, but presumably they would be path to input file, path to output file, and any processing options.

- `useMetanormaInvocationStatus()` should be called _as a hook_ in your React component, e.g.:

  ```tsx
  const mnStatusResponse = useMetanormaInvocationStatus();
  const mnStatus = mnStatusResponse.value;
  if (mnStatus !== null) {
    return <>
      <div>PID: {mnStatus.pid}</div>
      <textarea>{mnStatus.stdout}</textarea>
      <textarea css={css`color: red;`}>{mnStatus.stderr}</textarea>
      Exit code: {mnStatus.termination?.code ?? "(still running…)"}
     </>
  } else {
    return <>Metanorma process is not detected</>
  }
  ```

@wkwong-ribose maybe you can help me confirm whether this works for you.

To confirm your Paneron installation has Metanorma bundled, you can go to Paneron settings and scroll down to Metanorma path field (it should point to an executable, if it’s empty then executable was not bundled correctly, which [may be the case on Windows](https://github.com/paneron/paneron/issues/38)). If Metanorma is not bundled, `await invokeMetanorma()` will throw an error.

**Comment by wkwong-ribose** [comment]
<img width="587" alt="Screen Shot 2021-11-11 at 3 01 36 PM" src="https://user-images.githubusercontent.com/80878223/141252877-a0a1c451-5556-4cf9-848c-b35a35b1064b.png">

I don't think I can invoke Metanorma successfully.
I print the filename before invoking Metanorma.
Then, invokeMetanorma returns instantly without observable effect.
I tried `await invokeMetanorma`. It is still returning instantly.
Cannot catch any error too.
Not sure if the 'Failed to invoke method describeSubprocess' message is related. 

```tsx
Logger.logger.log('Filename', filename);
try {
  invokeMetanorma!({ cliArgs: ['-t', 'ribose', filename, '-o', '.'] });
} catch (e) {
  const error = e as Error;
  Logger.logger.log(error.message);
  Logger.logger.log(error.stack);
}
```

I also tested using useMetanormaInvocationStatus(). I think it simply cannot connect to metanorma now, so there is no information (stdout/stderr etc) shown. 

There are two other issues when I test the metanorma binary.
- The output could be more than one file, e.g., a webpage containing multiple files. If I want to post-process the output, I will need an ability to explore the contents inside a folder.
- Is it that the current file I/O can only be done by writeFileToFilesystem and requestFileFromFilesystem? They both must go through the open/save dialog before loading/saving. In the use case of Metanorma, I will need to put the contents in a temporary file. A mechanism to save a (temp) file without bothering the user would be great.

**Comment by strogonoff** [comment]
> Then, invokeMetanorma returns instantly without observable effect.

It is supposed to start the process and return instantly; after that, `useMetanormaInvocationStatus()` must be used to monitor invocation and termination status of the process.

**Comment by strogonoff** [comment]
> I also tested using useMetanormaInvocationStatus(). I think it simply cannot connect to metanorma now, so there is no information (stdout/stderr etc) shown.

I see, let me test that on your extension. @wkwong-ribose could you point to approximate component where you want to add GUI related to Metanorma?

**Comment by strogonoff** [comment]
> Is it that the current file I/O can only be done by writeFileToFilesystem and requestFileFromFilesystem? They both must go through the open/save dialog before loading/saving. In the use case of Metanorma, I will need to put the contents in a temporary file. A mechanism to save a (temp) file without bothering the user would be great.

- For manipulating files outside of repository, those two functions can be used. 
- For manipulating files inside the repository, `updateObjects()` and `useObjectData()` can be used.
- I will implement temp file mechanism shortly.

> The output could be more than one file, e.g., a webpage containing multiple files. If I want to post-process the output, I will need an ability to explore the contents inside a folder.

Yes, it is currently not possible to select a directory with multiple files using `requestFileFromFilesystem()`. I’m looking into addressing that limitation now.

**Comment by ronaldtse** [comment]
We will also need a way to access hidden functionality inside the Metanorma binary, e.g. the JAR functionality (mnconvert for STS => MN). I wonder if we need to update metanorma-cli to expose those functions.

**Comment by strogonoff** [comment]
> We will also need a way to access hidden functionality inside the Metanorma binary, e.g. the JAR functionality (mnconvert for STS => MN). I wonder if we need to update metanorma-cli to expose those functions.

IMO it should wrap any functionality into an API if it’s intended to be used from outside

**Comment by wkwong-ribose** [comment]
> > I also tested using useMetanormaInvocationStatus(). I think it simply cannot connect to metanorma now, so there is no information (stdout/stderr etc) shown.
> 
> I see, let me test that on your extension. @wkwong-ribose could you point to approximate component where you want to add GUI related to Metanorma?
> 
> > Not sure if the 'Failed to invoke method describeSubprocess' message is related.
> 
> It is related, I can see the problem, thank you. This should be addressed in the latest draft (https://github.com/paneron/paneron/releases/tag/untagged-c2f12ebcfdd4aee9edf9), currently building.

This file.
https://github.com/paneron/extension-hls/blob/dev/src/smart/ui/reporttemplate/MetanormaPrint.tsx#L16

**Comment by wkwong-ribose** [comment]
Metanorma can be invoked in Paneron now.

The next issue is how I can detect the end of the process.
I think Paneron keeps Metanorma running?
There is a PID already before I pass the CLI parameters to Metanorma.
The termination property is always undefined.

There is an isUpdating property but I think it is not related to the process?
It looks like isUpdating property means whether the state is being updated rather than the process is working.
I have seen isUpdating switching between true/false while nothing is passed to Metanorma.

stdout and stderr are working fine. A clear function would be nice.
The stdout and stderr will show the messages from the last call and that may be minutes ago.
It would be nice if when I call Metanorma, I can clear the stdout and stderr at that time.
Then, I would know the upcoming messages are generated from the new call.

**Comment by strogonoff** [comment]
> The next issue is how I can detect the end of the process. I think Paneron keeps Metanorma running? There is a PID already before I pass the CLI parameters to Metanorma. The termination property is always undefined.

Hmm. I identified an issue with termination not being handled correctly. Will publish a draft that resolves this shortly.

**Comment by strogonoff** [comment]
@wkwong-ribose 

> It would be nice if when I call Metanorma, I can clear the stdout and stderr at that time.

That’s the way it’s intended to work. Every invocation should clear `stdout` and `stderr`. However, since termination may not have been handled properly, I suspect it actually would not let you invoke Metanorma again without restarting the app? Anyway, let’s wait for https://github.com/paneron/paneron/commit/c048bd01c3a59a46e90eec1f4dab7995f4676097 to build beta22 draft binaries…

**Comment by strogonoff** [comment]
By the way, this call to [`refresh()`](https://github.com/paneron/extension-hls/blob/dev/src/smart/ui/reporttemplate/MetanormaPrint.tsx#L38) should not be necessary, because `useMetanormaInvocationStatus()` will [refresh itself](https://github.com/paneron/paneron/blob/master/src/datasets/renderer/context.ts#L363) whenever [subprocess events happen](https://github.com/paneron/paneron/blob/master/src/subprocesses/main.ts).

**Comment by wkwong-ribose** [comment]
In the beta22 version, I can run Metanorma once. Then, I cannot run it again.
Below is the error message from the console.

```
Error occurred in handler for 'execBundled': Error: Process is already running
    at /Applications/Paneron.app/Contents/Resources/app.asar/webpack:/src/subprocesses/main.ts:45:13
    at new Promise (<anonymous>)
    at /Applications/Paneron.app/Contents/Resources/app.asar/webpack:/src/subprocesses/main.ts:41:16
    at _handler (/Applications/Paneron.app/Contents/Resources/app.asar/webpack:/src/ipc.ts:216:30)
    at electron/js2c/browser_init.js:201:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10028)
    at Object.emit (events.js:315:20)
```
